import AppKit
import UniformTypeIdentifiers

/// A normalized snapshot of the pasteboard, before it becomes a stored `ClipItem`.
struct PasteboardDraft {
    var kind: ClipKind
    var text: String?
    var rtfData: Data?
    var imagePNG: Data?
    var imageWidth: Int?
    var imageHeight: Int?
    var fileURLs: [String]?
    var urlString: String?
    var colorHex: String?
    var sourceBundleID: String?
    var sourceAppName: String?
    var contentHash: String
}

@MainActor
enum PasteboardReader {
    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Convert the current pasteboard contents to a draft, or `nil` if it should be ignored.
    static func read(_ pb: NSPasteboard, settings: Settings) -> PasteboardDraft? {
        let types = Set(pb.types ?? [])

        // Skip secrets (password managers tag clips as concealed / transient).
        if settings.ignoreConcealed && !concealedTypes.isDisjoint(with: types) { return nil }

        // Source app (whatever was frontmost when the copy happened).
        let front = NSWorkspace.shared.frontmostApplication
        var sourceBundleID = front?.bundleIdentifier
        var sourceAppName = front?.localizedName
        if sourceBundleID == AppInfo.bundleID { sourceBundleID = nil; sourceAppName = nil }
        if let b = sourceBundleID, settings.excludedBundleIDs.contains(b) { return nil }

        func draft(_ kind: ClipKind,
                   text: String? = nil, rtf: Data? = nil, png: Data? = nil,
                   w: Int? = nil, h: Int? = nil, files: [String]? = nil,
                   url: String? = nil, color: String? = nil, hashSeed: Data) -> PasteboardDraft {
            PasteboardDraft(
                kind: kind, text: text, rtfData: rtf, imagePNG: png,
                imageWidth: w, imageHeight: h, fileURLs: files, urlString: url, colorHex: color,
                sourceBundleID: sourceBundleID, sourceAppName: sourceAppName,
                hash: hashSeed
            )
        }

        // 1) Files / folders
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            return draft(.file, files: paths, hashSeed: Data(paths.joined(separator: "\n").utf8))
        }

        // Keep the original string for fidelity; use a trimmed copy only for gating/classification.
        let rawString = pb.string(forType: .string)
        let trimmed = rawString?.trimmingCharacters(in: .whitespacesAndNewlines)

        // 2) Image (only when there's no accompanying text — avoids stealing rich text copies)
        if (trimmed?.isEmpty ?? true),
           let raw = pb.data(forType: .png) ?? pb.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: raw) {
            let png = rep.representation(using: .png, properties: [:]) ?? raw
            return draft(.image, png: png, w: rep.pixelsWide, h: rep.pixelsHigh, hashSeed: png)
        }

        // 3) Color swatch
        if pb.availableType(from: [.color]) != nil,
           let color = (pb.readObjects(forClasses: [NSColor.self], options: nil) as? [NSColor])?.first,
           let hex = color.hexString {
            return draft(.color, color: hex, hashSeed: Data(hex.utf8))
        }

        // 4) Rich text — keep the RTF; prefer the pasteboard's plain text, else derive it from the RTF
        //    (an RTF-only copy would otherwise be dropped). Hash includes the RTF so formatting-only
        //    re-copies aren't collapsed into one.
        if let rtf = pb.data(forType: .rtf), rtf.count < 2_000_000 {
            let plain: String? = (trimmed?.isEmpty == false)
                ? rawString
                : (try? NSAttributedString(
                        data: rtf,
                        options: [.documentType: NSAttributedString.DocumentType.rtf],
                        documentAttributes: nil))?.string
            if let p = plain, !p.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                return draft(.rtf, text: p, rtf: rtf, hashSeed: Data(p.utf8) + rtf)
            }
        }

        // 5) Plain text — preserve original whitespace; classify as a link if it's a single URL.
        if let t = trimmed, !t.isEmpty, let original = rawString {
            if isLink(t) {
                return draft(.link, text: t, url: t, hashSeed: Data(t.utf8))
            }
            return draft(.text, text: original, hashSeed: Data(original.utf8))
        }

        return nil
    }

    private static func isLink(_ s: String) -> Bool {
        guard !s.contains(where: \.isWhitespace), s.count < 2048 else { return false }
        guard let url = URL(string: s), let scheme = url.scheme?.lowercased() else { return false }
        return (scheme == "http" || scheme == "https") && url.host != nil
    }
}

extension PasteboardDraft {
    init(kind: ClipKind, text: String?, rtfData: Data?, imagePNG: Data?,
         imageWidth: Int?, imageHeight: Int?, fileURLs: [String]?, urlString: String?,
         colorHex: String?, sourceBundleID: String?, sourceAppName: String?, hash seed: Data) {
        self.kind = kind
        self.text = text
        self.rtfData = rtfData
        self.imagePNG = imagePNG
        self.imageWidth = imageWidth
        self.imageHeight = imageHeight
        self.fileURLs = fileURLs
        self.urlString = urlString
        self.colorHex = colorHex
        self.sourceBundleID = sourceBundleID
        self.sourceAppName = sourceAppName
        self.contentHash = ClipContentHash.make(kind: kind, seed: seed)
    }
}

extension NSColor {
    /// `#RRGGBB` (or `#RRGGBBAA` when not fully opaque) in sRGB.
    var hexString: String? {
        guard let c = usingColorSpace(.sRGB) else { return nil }
        let r = Int(round(c.redComponent * 255))
        let g = Int(round(c.greenComponent * 255))
        let b = Int(round(c.blueComponent * 255))
        let a = Int(round(c.alphaComponent * 255))
        return a == 255 ? String(format: "#%02X%02X%02X", r, g, b)
                        : String(format: "#%02X%02X%02X%02X", r, g, b, a)
    }
}
